# Generated by Django 3.0.5 on 2020-04-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='userName', max_length=32)),
                ('userID', models.IntegerField()),
                ('paperID', models.IntegerField()),
                ('contentView', models.TextField(null=True)),
                ('pubTime', models.DateTimeField(auto_now=True)),
                ('likeNum', models.IntegerField()),
                ('dislikeNum', models.IntegerField()),
                ('hot', models.IntegerField()),
                ('replyCommentID', models.IntegerField()),
                ('replyCommentUserName', models.CharField(default='repliedName', max_length=32)),
                ('avatar', models.ImageField(upload_to='')),
                ('replyNum', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-pubTime',),
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Arxiver.UserInfo')),
            ],
        ),
    ]
