# Generated by Django 3.0.3 on 2020-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arxiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='avatar',
            field=models.CharField(default='avatarID', max_length=200),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='paperID',
            field=models.CharField(default='PaperID', max_length=200),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='userID',
            field=models.CharField(default='USERID', max_length=32),
        ),
    ]
