# Generated by Django 3.0.3 on 2020-04-26 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Arxiver', '0002_auto_20200426_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='pubTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
