# Generated by Django 3.0.3 on 2020-05-03 12:08

import Arxiver.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arxiver', '0003_auto_20200426_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='dislikeUserIDList',
            field=Arxiver.models.ListField(default=['-1'], token=','),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='likeUserIDList',
            field=Arxiver.models.ListField(default=['-1'], token=','),
        ),
    ]
