# Generated by Django 3.0.3 on 2020-05-10 11:50

import Arxiver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arxiver', '0004_auto_20200503_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='userName', max_length=32)),
                ('password', models.CharField(default='000000', max_length=32)),
                ('profession', models.CharField(default='undefined', max_length=32)),
                ('email', models.CharField(default='undefined', max_length=32)),
                ('phoneNumber', models.CharField(default='undefined', max_length=32)),
                ('area', models.CharField(default='undefined', max_length=32)),
                ('personHomepage', models.CharField(default='undefined', max_length=200)),
                ('note', models.TextField(default='undefined')),
                ('headImg', models.ImageField(upload_to='img/')),
                ('isOnline', models.IntegerField(default=0)),
                ('collectList', Arxiver.models.ListField(token=',')),
                ('focusDict', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
