# Generated by Django 3.0.3 on 2020-05-12 06:44

import Arxiver.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arxiver', '0005_auto_20200510_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='focusDict',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='focusList',
            field=Arxiver.models.ListField(default=['-1'], token=','),
            preserve_default=False,
        ),
    ]
