# Generated by Django 3.0.3 on 2020-05-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arxiver', '0006_auto_20200512_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='collectList',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='collectDict',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
